### PR TITLE
Tests for py27,py35 with 100% coverage

### PR DESCRIPTION
**Pull request by sirex**
@solidsnack could you release new version of `linear-tsv` to pypi.python.org containing Python 3 support?

### CODE REVIEW

**Comment by solidsnack** [comment]
I am setting up a new computer and should be able to make the release in ~12 hours time.

**Comment by sirex** [comment]
Great, thanks. In that time I will fix #3 and #4.

**Comment by solidsnack** [comment]
I will fix all the non-PEP8 things and enable Travis

**Comment by solidsnack** [comment]
https://pypi.python.org/pypi/linear-tsv/0.99.0

**Comment by sirex** [comment]
Thanks.

**Pull request merged**
